name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        echo "No dependencies to install"

    - name: Run Application and Verify Output
      run: |
        OUTPUT=$(python app.py)
        echo "$OUTPUT"
        echo "$OUTPUT" | grep "Processing" || (echo "Expected output not found!" && exit 1)
